// 追加する問題
const List<Map<String, String>> questionContents = [
  {
    "question": "１行目と２行目をコメントアウトしてください",
    "code":
        "|||***|||これはサンプルコードですnnnconsole.log(“sample”);|||***|||nnnconsole.log(“hello world”);",
    "optionA": "\\",
    "optionB": "//",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "/*",
    "answerB": "*/",
  },
  {
    "question": "1行目と2行目をコメントアウトしてください",
    "code":
        "|||***|||これはサンプルコードですnnn|||***|||console.log(“sample”);nnnconsole.log(“hello world”);",
    "optionA": "//",
    "optionB": "\\",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "//",
    "answerB": "//",
  },
  {
    "question": "コンソールにhello worldと出力してください",
    "code": "// hello worldと出力しますnnn|||***|||(“|||***|||”);",
    "optionA": "print",
    "optionB": "console.log",
    "optionC": "sample  ",
    "optionD": "hello world",
    "answerA": "console.log",
    "answerB": "hello world",
  },
  {
    "question": "なにもコンソールに出力しない\nようにしてください。",
    "code": "|||***|||ここからnnnconsole.log(“output”);nnnここまで出力しない|||***|||",
    "optionA": "//",
    "optionB": "\\",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "/*",
    "answerB": "*/",
  },
  {
    "question": "晴れです。\nとコンソールに出力してください。",
    "code":
        "|||***|||console.log(“雨です。”);nnnconsole.log(“晴れです。”);nnn|||***|||console.log(“くもりです。”);",
    "optionA": "//",
    "optionB": "\\",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "//",
    "answerB": "//",
  },
  {
    "question": "こんばんわ。\nとコンソールに出力してください。",
    "code":
        "|||***|||console.log(“おはよう。”);nnnconsole.log(“こんにちは。”);|||***|||nnnconsole.log(“こんばんわ。”);",
    "optionA": "//",
    "optionB": "\\",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "/*",
    "answerB": "*/",
  },
  {
    "question": "コンソールにこんにちは。世界。\nと出力してください",
    "code":
        "|||***|||console.log(“おはよう。”);nnnconsole.log(“こんにちは。”);nnn|||***|||(“世界。”);",
    "optionA": "print",
    "optionB": "console.log",
    "optionC": "//",
    "optionD": "\\",
    "answerA": "//",
    "answerB": "console.log",
  },
  {
    "question": "コンソールにぼくの。名前は。ジェスです。\nと出力してください",
    "code":
        "console.log(“ぼくの。”);nnnconsole.log(“|||***|||”);nnnconsole.log(“|||***|||”);",
    "optionA": "ジェスです。",
    "optionB": "トムです。",
    "optionC": "名前は",
    "optionD": "名前は。",
    "answerA": "名前は。",
    "answerB": "ジェスです。",
  },
  {
    "question": "コンソールに ”今日は散歩です” \nと出力してください",
    "code":
        "// 今日は散歩ですを出力;nnnconsole.log(“|||***|||”);nnn|||***|||.log(“散歩です”);",
    "optionA": "今日は",
    "optionB": "本日は",
    "optionC": "console",
    "optionD": "print",
    "answerA": "今日は",
    "answerB": "console",
  },
  {
    "question": "コンソールに ”気分転換は大事” \nと出力してください",
    "code":
        "// 気分転換は大事を出力;nnnconsole.|||***|||(“気分転換は”);nnnconsole.log(“|||***|||”);",
    "optionA": "log",
    "optionB": "debug",
    "optionC": "だいじ",
    "optionD": "大事",
    "answerA": "log",
    "answerB": "大事",
  },
  {
    "question": "コンソールに出力するために\n正しいコードはどれ？",
    "code": "|||***|||.|||***|||(“hello world”);",
    "optionA": "print",
    "optionB": "debug",
    "optionC": "log",
    "optionD": "console",
    "answerA": "console",
    "answerB": "log",
  },
  {
    "question": "エラーが出ないように\n正しいコードに修正してください",
    "code": "|||***|||print(“今日はいい日”);nnn|||***|||.log(“今日はいい天気”);",
    "optionA": "console",
    "optionB": "debug",
    "optionC": "\\",
    "optionD": "//",
    "answerA": "//",
    "answerB": "console",
  },
];
