// 追加する問題
const List<Map<String, String>> questionContents = [
  {
    "question": "１行目と２行目をコメントアウトしてください",
    "code":
        "|||***|||これはサンプルコードですnnnconsole.log(“sample”);|||***|||nnnconsole.log(“hello world”);",
    "optionA": "\\",
    "optionB": "//",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "/*",
    "answerB": "*/",
  },
  {
    "question": "1行目と2行目をコメントアウトしてください",
    "code":
        "|||***|||これはサンプルコードですnnn|||***|||console.log(“sample”);nnnconsole.log(“hello world”);",
    "optionA": "//",
    "optionB": "\\",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "//",
    "answerB": "//",
  },
  {
    "question": "コンソールにhello worldと出力してください",
    "code": "// hello worldと出力しますnnn|||***|||(“|||***|||”);",
    "optionA": "print",
    "optionB": "console.log",
    "optionC": "sample  ",
    "optionD": "hello world",
    "answerA": "console.log",
    "answerB": "hello world",
  },
  {
    "question": "なにもコンソールに出力しない\nようにしてください。",
    "code": "|||***|||ここからnnnconsole.log(“output”);nnnここまで出力しない|||***|||",
    "optionA": "//",
    "optionB": "\\",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "/*",
    "answerB": "*/",
  },
  {
    "question": "晴れです。\nとコンソールに出力してください。",
    "code":
        "|||***|||console.log(“雨です。”);nnnconsole.log(“晴れです。”);nnn|||***|||console.log(“くもりです。”);",
    "optionA": "//",
    "optionB": "\\",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "//",
    "answerB": "//",
  },
  {
    "question": "こんばんわ。\nとコンソールに出力してください。",
    "code":
        "|||***|||console.log(“おはよう。”);nnnconsole.log(“こんにちは。”);|||***|||nnnconsole.log(“こんばんわ。”);",
    "optionA": "//",
    "optionB": "\\",
    "optionC": "/*",
    "optionD": "*/",
    "answerA": "/*",
    "answerB": "*/",
  },
  {
    "question": "コンソールにこんにちは。世界。\nと出力してください",
    "code":
        "|||***|||console.log(“おはよう。”);nnnconsole.log(“こんにちは。”);nnn|||***|||(“世界。”);",
    "optionA": "print",
    "optionB": "console.log",
    "optionC": "//",
    "optionD": "\\",
    "answerA": "//",
    "answerB": "console.log",
  },
  {
    "question": "コンソールにぼくの。名前は。ジェスです。\nと出力してください",
    "code":
        "console.log(“ぼくの。”);nnnconsole.log(“|||***|||”);nnnconsole.log(“|||***|||”);",
    "optionA": "ジェスです。",
    "optionB": "トムです。",
    "optionC": "名前は",
    "optionD": "名前は。",
    "answerA": "名前は。",
    "answerB": "ジェスです。",
  },
  {
    "question": "コンソールに ”今日は散歩です” \nと出力してください",
    "code":
        "// 今日は散歩ですを出力;nnnconsole.log(“|||***|||”);nnn|||***|||.log(“散歩です”);",
    "optionA": "今日は",
    "optionB": "本日は",
    "optionC": "console",
    "optionD": "print",
    "answerA": "今日は",
    "answerB": "console",
  },
  {
    "question": "コンソールに ”気分転換は大事” \nと出力してください",
    "code":
        "// 気分転換は大事を出力;nnnconsole.|||***|||(“気分転換は”);nnnconsole.log(“|||***|||”);",
    "optionA": "log",
    "optionB": "debug",
    "optionC": "だいじ",
    "optionD": "大事",
    "answerA": "log",
    "answerB": "大事",
  },
  {
    "question": "コンソールに出力するために\n正しいコードはどれ？",
    "code": "|||***|||.|||***|||(“hello world”);",
    "optionA": "print",
    "optionB": "debug",
    "optionC": "log",
    "optionD": "console",
    "answerA": "console",
    "answerB": "log",
  },
  {
    "question": "エラーが出ないように\n正しいコードに修正してください",
    "code": "|||***|||print(“今日はいい日”);nnn|||***|||.log(“今日はいい天気”);",
    "optionA": "console",
    "optionB": "debug",
    "optionC": "\\",
    "optionD": "//",
    "answerA": "//",
    "answerB": "console",
  },
  {
    "question": "『 文字列 』と『 数字 』を\n出力してください。",
    "code":
        "// 文字列を出力nnnconsole.log(|||***|||);nnn// 数字を出力nnnconsole.log(|||***||| + %);",
    "optionA": '"晴れ"',
    "optionB": 'くもり',
    "optionC": "100",
    "optionD": '100%',
    "answerA": '"晴れ"',
    "answerB": "100",
  },
  {
    "question": "計算をして『 23 』と出力してください。",
    "code": "console.log(|||***||| |||***||| 4);",
    "optionA": '*',
    "optionB": '19',
    "optionC": "+",
    "optionD": '"11"',
    "answerA": '19',
    "answerB": "+",
  },
  {
    "question": "各コメントに対して正しいものはどれ？",
    "code":
        "// 43と出力nnnconsole.log(|||***||| + 3);nnn// 50と出力nnnconsole.log(|||***||| * 2);",
    "optionA": '25',
    "optionB": '7',
    "optionC": '"25"',
    "optionD": '"4"',
    "answerA": '"4"',
    "answerB": "25",
  },
  {
    "question": "『 変数 』を作成してください。",
    "code": '|||***||| weather |||***||| "はれ";',
    "optionA": '+',
    "optionB": '=',
    "optionC": 'var',
    "optionD": 'const',
    "answerA": 'var',
    "answerB": '=',
  },
  {
    "question": "『 定数 』を作成してください。",
    "code": '|||***||| height |||***||| 170;',
    "optionA": '+',
    "optionB": '=',
    "optionC": 'var',
    "optionD": 'const',
    "answerA": 'const',
    "answerB": '=',
  },
  {
    "question": "『 43 』と出力してください。",
    "code": 'var age = 42;nnn|||***||| |||***||| 43;nnnconsole.log(age);',
    "optionA": '+',
    "optionB": '=',
    "optionC": 'var',
    "optionD": 'age',
    "answerA": 'age',
    "answerB": '=',
  },
  {
    "question": "『 定数のエラー 』となるように\n空白を埋めてください。",
    "code":
        '|||***||| name = "はむれこ はむ";nnn|||***||| = 城之内; error!!nnnconsole.log(name);',
    "optionA": 'var',
    "optionB": 'const',
    "optionC": 'name',
    "optionD": 'age',
    "answerA": 'const',
    "answerB": 'name',
  },
  {
    "question": "各コメントに対して正しいコードは？",
    "code":
        '// 変数を作成nnn|||***||| color = "black";nnn// 『今日のコーデは黒』と出力nnnconsole.log("今日のコーデは |||***||| color");',
    "optionA": 'var',
    "optionB": 'const',
    "optionC": '+',
    "optionD": '*',
    "answerA": 'var',
    "answerB": '+',
  },
  {
    "question": "『 180 』と出力してください。",
    "code":
        'const firstNum = 80;nnnconst secondNum = |||***|||;nnnconsole.log(fristNum |||***||| secondNum);',
    "optionA": '+',
    "optionB": '100',
    "optionC": '120',
    "optionD": '*',
    "answerA": '100',
    "answerB": '+',
  },
  {
    "question": "正しくなるように空白を埋めてください。",
    "code":
        'const name = "もれ子";nnn|||***||| familyName = 鈴木;nnn// 結婚したから姓が変わったnnn|||***||| = "山口";nnnconsole.log(familyName + name);',
    "optionA": 'name',
    "optionB": 'const',
    "optionC": 'var',
    "optionD": 'familyName',
    "answerA": 'var',
    "answerB": 'familyName',
  },
  {
    "question": "『 元気100倍 』と出力してください。",
    "code": 'const num = 100;nnnconsole.log("元気" + |||***||| + |||***|||);',
    "optionA": '倍',
    "optionB": '"倍"',
    "optionC": 'num',
    "optionD": '100倍',
    "answerA": 'num',
    "answerB": '"倍"',
  },
  {
    "question": "『 5 』となるように計算をしてください。",
    "code": 'const num = 100;nnnconsole.log(num |||***||| |||***|||);',
    "optionA": '@',
    "optionB": '/',
    "optionC": '25',
    "optionD": '20',
    "answerA": '/',
    "answerB": '20',
  },
  {
    "question": "各コメントが正しくなるように\n計算をしてください。",
    "code":
        '// 『 10 』と出力nnnconsole.log(2 |||***||| 5);nnn// 『 2 』と出力nnnconsole.log(10 |||***||| 5);',
    "optionA": '+',
    "optionB": '-',
    "optionC": '*',
    "optionD": '/',
    "answerA": '*',
    "answerB": '/',
  },
  {
    "question": "『 定数のエラー 』となるように\n空白を埋めてください。",
    "code": '|||***||| age = "10";nnn|||***||| = 11; error!!',
    "optionA": 'var',
    "optionB": 'const',
    "optionC": 'name',
    "optionD": 'age',
    "answerA": 'const',
    "answerB": 'age',
  },
  {
    "question": "計算をしてください。",
    "code": '// 『 30 』と出力nnnconsole.log(3 |||***||| |||***|||);',
    "optionA": '+',
    "optionB": '*',
    "optionC": '27',
    "optionD": '"27"',
    "answerA": '+',
    "answerB": '27',
  },
  {
    "question": "『 好きな食べ物は魚 』と\n出力してください。",
    "code":
        '|||***||| food = "肉";nnnconst favorite = "好きな食べ物は";nnn|||***||| = "魚";nnnconsole.log(favorite + food);',
    "optionA": 'favorite',
    "optionB": 'food',
    "optionC": 'var',
    "optionD": 'const',
    "answerA": 'var',
    "answerB": 'food',
  },
  {
    "question": "『 変数 』を作成してください。",
    "code": '|||***||| location |||***||| "japan";',
    "optionA": '=',
    "optionB": 'const',
    "optionC": 'var',
    "optionD": '+',
    "answerA": 'var',
    "answerB": '=',
  },
  {
    "question": "『 わかりやすい変数名 』をつけてください。",
    "code": '// 『 車種 』の変数を作成nnn|||***||| |||***||| = "ホンダ";',
    "optionA": 'var',
    "optionB": 'name',
    "optionC": 'car',
    "optionD": 'carModel',
    "answerA": 'var',
    "answerB": 'carModel',
  },
];
